# Generated by Django 2.1 on 2018-09-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleApp', '0002_auto_20180906_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='essentialExpenses',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='locations',
            field=models.CharField(choices=[('AMK', 'Ang Mo Kio'), ('SRG', 'Serangoon'), ('WLDS', 'Woodlands')], max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='monthlyIncome',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='personalSavings',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
