# Generated by Django 2.1 on 2018-09-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleApp', '0004_auto_20180908_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='email',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='name',
        ),
        migrations.AddField(
            model_name='snippet',
            name='availDownPay',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='existingLoan',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
