# Generated by Django 2.1 on 2018-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleApp', '0006_auto_20180908_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='y1',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='YES', max_length=1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='y2',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='YES', max_length=1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='y3',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='YES', max_length=1),
        ),
    ]
